CREATE TABLE BLISCY
(
  ID_OSOBY     INT         NULL    ,
  ID_BLISKIEGO INT         NULL    ,
  TYP_RELACJI  VARCHAR(50) NULL    ,
  PRIMARY KEY (ID_OSOBY, ID_BLISKIEGO)
);

CREATE TABLE GARAZ
(
  ID_MASZYNY INT         NULL    ,
  ID_POJAZDU INT         NULL    ,
  STATUS     VARCHAR(50) NULL    ,
  PRIMARY KEY (ID_MASZYNY)
);

CREATE TABLE OBSLUGA
(
  ID_PODROZY    INT NULL    ,
  ID_PRACOWNIKA INT NULL    ,
  PRIMARY KEY (ID_PODROZY, ID_PRACOWNIKA)
);

CREATE TABLE OSOBY
(
  ID_OSOBY       INT          NULL    ,
  IMIE           VARCHAR(50)  NULL    ,
  NAZWISKO       VARCHAR(50)  NULL    ,
  DATA_URODZENIA DATE         NULL    ,
  EMAIL          VARCHAR(100) NULL    ,
  TELEFON        VARCHAR(20)  NULL    ,
  ULICA          VARCHAR(100) NULL    ,
  MIEJSCOWOSC    VARCHAR(100) NULL    ,
  KOD_POCZTOWY   VARCHAR(10)  NULL    ,
  ID_STACJI      INT          NULL    ,
  PRIMARY KEY (ID_OSOBY)
);

CREATE TABLE PASAZEROWIE
(
  ID_PODROZY   INT     NULL    ,
  ID_OSOBY     INT     NULL    ,
  ID_PLATNOSCI INT     NULL    ,
  NA_POKLADZIE BOOLEAN NULL    ,
  PRIMARY KEY (ID_PODROZY, ID_OSOBY)
);

CREATE TABLE PLATNOSCI
(
  ID_PLATNOSCI     INT           NULL    ,
  ZAPLACONA_KWOTA  DECIMAL(10,2) NULL    ,
  WALUTA           VARCHAR(10)   NULL    ,
  DATA_PLATNOSCI   DATE          NULL    ,
  METODA_PLATNOSCI VARCHAR(50)   NULL    ,
  PRIMARY KEY (ID_PLATNOSCI)
);

CREATE TABLE PODROZE
(
  ID_PODROZY   INT           NULL    ,
  ID_TRASY     INT           NULL    ,
  ID_POJAZDU   INT           NULL    ,
  DATA_START   DATETIME      NULL    ,
  DATA_KONIEC  DATETIME      NULL    ,
  KOSZT        DECIMAL(15,2) NULL    ,
  ID_PLATNOSCI INT           NULL    ,
  STATUS       VARCHAR(50)   NULL    ,
  PRIMARY KEY (ID_PODROZY)
);

CREATE TABLE POJAZDY
(
  ID_POJAZDU   INT          NULL    ,
  PRODUCENT    VARCHAR(100) NULL    ,
  MODEL        VARCHAR(100) NULL    ,
  ZASIEG_KM    INT          NULL    ,
  PREDKOSC_MAX INT          NULL    ,
  TYP_POJAZDU  VARCHAR(50)  NULL    ,
  POJEMNOSC    INT          NULL    ,
  PRIMARY KEY (ID_POJAZDU)
);

CREATE TABLE PRACOWNICY
(
  ID_PRACOWNIKA INT          NULL    ,
  ID_OSOBY      INT          NULL    ,
  STANOWISKO    VARCHAR(100) NULL    ,
  DATA_POCZATEK DATE         NULL    ,
  DATA_KONIEC   DATE         NULL    ,
  PRIMARY KEY (ID_PRACOWNIKA)
);

CREATE TABLE SERWIS
(
  ID_SERWISU       INT           NULL    ,
  ID_MASZYNY       INT           NULL    ,
  DATA_ROZPOCZECIA DATE          NULL    ,
  DATA_ZAKONCZENIA DATE          NULL    ,
  OPIS             TEXT          NULL    ,
  KOSZT            DECIMAL(10,2) NULL    ,
  PRIMARY KEY (ID_SERWISU)
);

CREATE TABLE STACJE
(
  ID_STACJI       INT   NULL    ,
  POLOZENIE_R     FLOAT NULL    ,
  POLOZENIE_THETA FLOAT NULL    ,
  POLOZENIE_PHI   FLOAT NULL    ,
  OPIS_STACJI    TEXT  NULL    ,
  PRIMARY KEY (ID_STACJI)
);

CREATE TABLE TRASY
(
  ID_TRASY         INT NULL    ,
  ID_STACJA_START  INT NULL    ,
  ID_STACJA_KONIEC INT NULL    ,
  DLUGOSC_TRASY    INT NULL    ,
  PRIMARY KEY (ID_TRASY)
);

ALTER TABLE OSOBY
  ADD CONSTRAINT FK_STACJE_TO_OSOBY
    FOREIGN KEY (ID_STACJI)
    REFERENCES STACJE (ID_STACJI);

ALTER TABLE BLISCY
  ADD CONSTRAINT FK_OSOBY_TO_BLISCY
    FOREIGN KEY (ID_OSOBY)
    REFERENCES OSOBY (ID_OSOBY);

ALTER TABLE BLISCY
  ADD CONSTRAINT FK_OSOBY_TO_BLISCY1
    FOREIGN KEY (ID_BLISKIEGO)
    REFERENCES OSOBY (ID_OSOBY);

ALTER TABLE PRACOWNICY
  ADD CONSTRAINT FK_OSOBY_TO_PRACOWNICY
    FOREIGN KEY (ID_OSOBY)
    REFERENCES OSOBY (ID_OSOBY);

ALTER TABLE GARAZ
  ADD CONSTRAINT FK_POJAZDY_TO_GARAZ
    FOREIGN KEY (ID_POJAZDU)
    REFERENCES POJAZDY (ID_POJAZDU);

ALTER TABLE SERWIS
  ADD CONSTRAINT FK_GARAZ_TO_SERWIS
    FOREIGN KEY (ID_MASZYNY)
    REFERENCES GARAZ (ID_MASZYNY);

ALTER TABLE TRASY
  ADD CONSTRAINT FK_STACJE_TO_TRASY
    FOREIGN KEY (ID_STACJA_START)
    REFERENCES STACJE (ID_STACJI);

ALTER TABLE TRASY
  ADD CONSTRAINT FK_STACJE_TO_TRASY1
    FOREIGN KEY (ID_STACJA_KONIEC)
    REFERENCES STACJE (ID_STACJI);

ALTER TABLE PODROZE
  ADD CONSTRAINT FK_TRASY_TO_PODROZE
    FOREIGN KEY (ID_TRASY)
    REFERENCES TRASY (ID_TRASY);

ALTER TABLE PODROZE
  ADD CONSTRAINT FK_POJAZDY_TO_PODROZE
    FOREIGN KEY (ID_POJAZDU)
    REFERENCES POJAZDY (ID_POJAZDU);

ALTER TABLE PODROZE
  ADD CONSTRAINT FK_PLATNOSCI_TO_PODROZE
    FOREIGN KEY (ID_PLATNOSCI)
    REFERENCES PLATNOSCI (ID_PLATNOSCI);

ALTER TABLE OBSLUGA
  ADD CONSTRAINT FK_PODROZE_TO_OBSLUGA
    FOREIGN KEY (ID_PODROZY)
    REFERENCES PODROZE (ID_PODROZY);

ALTER TABLE OBSLUGA
  ADD CONSTRAINT FK_PRACOWNICY_TO_OBSLUGA
    FOREIGN KEY (ID_PRACOWNIKA)
    REFERENCES PRACOWNICY (ID_PRACOWNIKA);

ALTER TABLE PASAZEROWIE
  ADD CONSTRAINT FK_PODROZE_TO_PASAZEROWIE
    FOREIGN KEY (ID_PODROZY)
    REFERENCES PODROZE (ID_PODROZY);

ALTER TABLE PASAZEROWIE
  ADD CONSTRAINT FK_OSOBY_TO_PASAZEROWIE
    FOREIGN KEY (ID_OSOBY)
    REFERENCES OSOBY (ID_OSOBY);

ALTER TABLE PASAZEROWIE
  ADD CONSTRAINT FK_PLATNOSCI_TO_PASAZEROWIE
    FOREIGN KEY (ID_PLATNOSCI)
    REFERENCES PLATNOSCI (ID_PLATNOSCI);
